### ISSUE TITLE
Docker Build Fail

### ISSUE THREAD

**Issue by dhonxean** [CNES/decloud#9]
Hello.

I tried building the Dockerfile but I got this error that the mdl4eo/otbtf3.3.2:gpu-dev: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed. Is the docker image not accessible?

What I did:

cd to decloud directory
docker build .

Kindly see attached image for reference of the error. Thank you!

![image](https://github.com/CNES/decloud/assets/31211845/8ee64c5c-2737-457e-a42c-a7df464de6ad)

**Comment by remicres** [comment]
hello @dhonxean we have changed the docker images names: now they are named after the semantic versioning: `mdl4eo/otbtf:X.Y.Z-suffix[-dev]`, where:

-    `X.Y.Z` is the OTBTF version
-    suffix is either cpu or gpu
-    `-dev` is for development ready images (with OTB and TensorFlow C++ sources)

I am fixing the reference right now in the CI and the dockerfile, stay tuned!

**Comment by dhonxean** [comment]
Thank you very much for all the hardwork! Will definitely stay tuned!

**Comment by remicres** [comment]
you can try with the [fix_docker_build](https://github.com/CNES/decloud/tree/fix_docker_build) branch, it should build. For now our CI is running tests: as soon as they all pass we will merge this in the main branch.

**Comment by dhonxean** [comment]
I had successfully ran the docker image. Thank you!!!
